stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - data/data_raw.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/data_raw.csv
    metrics:
      - metrics.json
    plots:
      - confusion_matrix.png
